//
//  DarkMode.swift
//  SSKeyboardHue
//
//  Created by ErrorErrorError on 11/6/19.
//  Copyright © 2019 . All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import Cocoa

public class DarkMode : NSObject {

    private struct Cache {
        static let subviews: NSColor = NSColor(red: 0.106, green: 0.106, blue: 0.106, alpha: 1.0)
        static let background: NSColor = NSColor(red: 0.086, green: 0.086, blue: 0.086, alpha: 1.0)
        static let sideview: NSColor = NSColor(red: 0.118, green: 0.118, blue: 0.118, alpha: 1)
        static let textViewBackground: NSColor = RGB(r: 52, g: 52, b: 52).nsColor
    }

    @objc dynamic public class var subviews: NSColor { return Cache.subviews }
    @objc dynamic public class var background: NSColor { return Cache.background }
    @objc dynamic public class var sideview: NSColor { return Cache.sideview }
    @objc dynamic public class var textViewBackground: NSColor { return Cache.textViewBackground }
}
